<?php
$tp = asset('themes/lte');
$k = md5(date('YmddmY'));
?>
<!DOCTYPE html>
<!DOCTYPE html>
<html class="lockscreen">
    <head>
        <meta charset="UTF-8">
        <title>PIE IOT</title>
        <link href="{{asset('images/pie.ico')}}" rel="shortcut icon">
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="{{$tp}}/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="{{$tp}}/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="{{$tp}}/css/AdminLTE.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body data-root="{{asset('/')}}">
        <!-- Automatic element centering using js -->
        <div class="center">            
            <div class="headline text-center" id="time">
                <!-- Time auto generated by js -->
            </div><!-- /.headline -->

            <!-- User name -->
            <div>
                <div class="body">
                    <form id="formlogin">
                        <div class="form-group">
                            <input type="text" name="txuname" class="form-control" placeholder="User ID">
                        </div>
                        <div class="form-group">
                            <input type="password" name="txpwd" class="form-control" placeholder="Password">
                        </div>          
                        <div class="form-group">
                            <label><input type="checkbox" name="remember_me"> Remember me</label>
                        </div>
                        <input name='k' type='hidden' id='k' value='{{$k}}' />
                        <input name='oldpath' type='hidden' id='oldpath' value='edoc' />
                    </form>
                </div>
                <div class="footer">                                                               
                    <button  class="btn bg-olive btn-block btnlogin">Sign me in</button>  
                    <div id="divload" class="p2 hidden text-center">
                        <img src="{{asset('images/loading.gif')}}" style="width: 30px;">    
                        กำลังดำเนินการ...             
                    </div>
                </div>
            </div>
            <div class="lockscreen-link">
                <p><a href="#">I forgot my password</a></p>

                <a href="register.html" class="text-center">Register a new membership</a>
                <a href="login.html">Or sign in as a different user</a>
            </div>            
        </div><!-- /.center -->
        <div id="alertModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="p_title">HRD System</h3>
            </div>
            <div class="modal-body">
                <p id="p_msg">Are you sure you wish to delete?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">OK</button>
            </div>
        </div> 

        <!-- jQuery 2.0.2 -->
        <script src="{{$tp}}/js/jquery.min.js" type="text/javascript"></script>
        <!-- Bootstrap -->
        <script src="{{$tp}}/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="{{asset('/')}}js/piescript.js" type="text/javascript"></script>
        <script src="{{asset('/')}}js/bootbox.min.js" type="text/javascript"></script>
        <!-- page script -->
        <script type="text/javascript">
$(function () {
    startTime();
    $(".center").center();
    $(window).resize(function () {
        $(".center").center();
    });
});

/*  */
function startTime()
{
    var today = new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();

    // add a zero in front of numbers<10
    m = checkTime(m);
    s = checkTime(s);

    //Check for PM and AM
    var day_or_night = (h > 11) ? "PM" : "AM";

    //Convert to 12 hours system
    if (h > 12)
        h -= 12;

    //Add time to the headline and update every 500 milliseconds
    $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
    setTimeout(function () {
        startTime()
    }, 500);
}

function checkTime(i)
{
    if (i < 10)
    {
        i = "0" + i;
    }
    return i;
}

/* CENTER ELEMENTS IN THE SCREEN */
jQuery.fn.center = function () {
    this.css("position", "absolute");
    this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
            $(window).scrollTop()) - 30 + "px");
    this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
            $(window).scrollLeft()) + "px");
    return this;
}
        </script>
    </body>
</html>

